### ISSUE TITLE
Not positioning image correctly

### ISSUE THREAD

**Issue by jfredson** [VuongN/jQuery-Fakecrop#3]
Hello,

I have inherited a Shopify store with a custom theme that is using this script to crop and position the product images on a collection page.

For some reason, some images don't seem to be getting positioned correctly and I can't figure out exactly why. I have attached a screenshot of one example.

The css that is getting applied to the image is:

`position: absolute;
top: 0px;
left: -46.60352422907491px;
height: 298px;
width: 391.2070484581498px;`

All the other images that are positioned correctly have the "left" attribute set to "0". How would I go about fixing this issue so that this image in particular is being set to "left: 0" as well?

**Comment by VuongN** [comment]
It would be pretty hard to debug without an actual thing to poke at. Do you have anyway to show me what you're seeing?

**Comment by jfredson** [comment]
Hey, thanks for the quick response. The page in question is at https://satorisagharbor.com/collections/accessories

The second product is the one that is displaying incorrectly.

John

**Comment by VuongN** [comment]
Okay, I believe I understand the issue. The offset calculation uses image's dimensions to center the image in the square. This was the original intent - however, in this instance it looks bad because images of the glasses are taken in a 3/4 angle, so the centering makes the image look off. The only way to fix it, is to make the image files have square dimensions. You can see that the images with dimension 480x480 look fine but images #2 & #9 are rectangular.

**Comment by jfredson** [comment]
That’s what I figured and that’s the advice I’ve given the client for now. I appreciate your quick response and diagnosis though. It’s never easy adopting someone else’s code base and trying to decipher these things!

John

**Comment by VuongN** [comment]
No problem. Will close this ticket for now.
